[connections.my_database_2]
    type="sql"
    dialect="mysql"
    username="admin"
    password="d0a321ce-d56b-4496-98a5-23cd179363ea"
    host="kivid-dev.chdrraxrtssq.us-east-2.rds.amazonaws.com" # IP or URL
    port=3306 # Port number
    database="kividhmg" # Database name
[connections.my_database]
    type="sql"
    dialect="mysql"
    username="admin"
    password="f868a40a-a3d1-4331-a73a-b30f7bf8b4d7"
    host="kivid-prod.chdrraxrtssq.us-east-2.rds.amazonaws.com" # IP or URL
    port=3306 # Port number
    database="kivid" # Database name
    